export const FETCH_MEMO_LIST_REQUEST = 'FETCH_MEMO_LIST_REQUEST'
export const FETCH_MEMO_LIST_SUCCESS = 'FETCH_MEMO_LIST_SUCCESS'
export const FETCH_MEMO_LIST_FAILURE = 'FETCH_MEMO_LIST_FAILURE'

export const FETCH_DELETED_MEMO_LIST_REQUEST = 'FETCH_DELETED_MEMO_LIST_REQUEST'
export const FETCH_DELETED_MEMO_LIST_SUCCESS = 'FETCH_DELETED_MEMO_LIST_SUCCESS'
export const FETCH_DELETED_MEMO_LIST_FAILURE = 'FETCH_DELETED_MEMO_LIST_FAILURE'

export const FETCH_MEMO_REQUEST = 'FETCH_MEMO_REQUEST'
export const FETCH_MEMO_SUCCESS = 'FETCH_MEMO_SUCCESS'
export const FETCH_MEMO_FAILURE = 'FETCH_MEMO_FAILURE'

export const FETCH_DELETED_MEMO_REQUEST = 'FETCH_DELETED_MEMO_REQUEST'
export const FETCH_DELETED_MEMO_SUCCESS = 'FETCH_DELETED_MEMO_SUCCESS'
export const FETCH_DELETED_MEMO_FAILURE = 'FETCH_DELETED_MEMO_FAILURE'

export const ADD_MEMO_REQUEST = 'ADD_MEMO_REQUEST'
export const ADD_MEMO_SUCCESS = 'ADD_MEMO_SUCCESS'
export const ADD_MEMO_FAILURE = 'ADD_MEMO_FAILURE'

export const DELETE_MEMO_REQUEST = 'DELETE_MEMO_REQUEST'
export const DELETE_MEMO_SUCCESS = 'DELETE_MEMO_SUCCESS'
export const DELETE_MEMO_FAILURE = 'DELETE_MEMO_FAILURE'

export const RESTORE_MEMO_REQUEST = 'RESTORE_MEMO_REQUEST'
export const RESTORE_MEMO_SUCCESS = 'RESTORE_MEMO_SUCCESS'
export const RESTORE_MEMO_FAILURE = 'RESTORE_MEMO_FAILURE'


export const CLEAR_API_CALL_STATUS = 'CLEAR_API_CALL_STATUS'

export const SHOW_TOAST = 'SHOW_TOAST'
export const ADD_TOAST = 'ADD_TOAST'
export const REMOVE_TOAST = 'REMOVE_TOAST'

export const SHOW_DIALOG = 'SHOW_DIALOG'
export const CONFIRM_DIALOG = 'CONFIRM_DIALOG'
export const CANCEL_DIALOG = 'CANCEL_DIALOG'